"""Table Modify

Revision ID: f406f9e2b11b
Revises: a30fd9b95bdc
Create Date: 2022-10-26 01:07:25.519178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f406f9e2b11b'
down_revision = 'a30fd9b95bdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
